/**
 * Types Index
 * Central export point for all type definitions
 */

// Export database types
export type {
    Transaction,
    Pengeluaran,
    PengeluaranCategory,
    TagihanBulanan,
    TagihanFeeLunas,
    TagihanFeeLunasItem,
    LokasiApartemen,
    NomorKamar,
    KaryawanList,
    MarketingList,
    Request,
    UserProfile,
    UserRoleRow,
    UserLocationAssignment,
    UserPermission,
    ActivityLog,
    MenuAccessLog,
    MenuConfiguration,
    RoleMenuVisibility,
    Notification,
    NotificationHidden,
    NotificationPreference,
    NotificationRead,
    PushSubscription,
    SystemSetting,
    AppSetting,
    AiProviderModel,
    AiInsightCache,
    KraiConversation,
    KraiSetting,
    AnalyticsQueryCache,
    AnalyticsCacheMart,
    Database,
    UnitStatus,
    RequestStatus,
    BillStatus,
    UserRole,
} from './database';

// Export dashboard types
export type {
    KPIData,
    KPIChange,
    KPICompareMode,
    RevenueDataPoint,
    RevenueFilter,
    OccupancyDataPoint,
    CheckinItem,
    CheckoutItem,
    UnitStatusCounts,
    UnitStatus as DashboardUnitStatus,
    UnitIdleSeverity,
    IdleUnitItem,
    UnitPerformanceItem,
    LocationHealthStatus,
    LocationHealthItem,
    InsightSeverity,
    InsightTrend,
    MarketingPerformanceStatus,
    MarketingPerformanceItem,
    DashboardInsight,
    ExpenseItem,
    ExpenseCategory,
    BookingTableItem,
    ReportPeriod,
    DashboardFilterParams,
    ApiResponse,
    DashboardTabConfig,
} from './dashboard';

// Export analytics types
export type {
    DashboardKPIs,
    DailyRevenueTrend,
    MonthlyRevenueTrend,
    OccupancyPerLocation,
    OccupancyPerUnit,
    LocationFullness,
    ExpenseBreakdown,
    CategorySummary,
    MarketingPerformance,
    GuestSourceSummary,
    NetProfitPerLocation,
    ProfitPerLocation,
    PaymentMethodSummary,
    PerformanceByEmployee,
    PerformanceByShift,
    RepeatGuest,
    StayDurationSummary,
    CheckinHeatmap,
    OutstandingBillsSummary,
    UnderperformingRoom,
    RevenueYoYComparison,
    DashboardAggregatedData,
} from './analytics';

// Export AI types
export type {
    AIInsightRequest,
    AIInsightResponse,
    AIInsightCacheEntry,
    ChatMessage,
    KraiConversation as KraiConversationDTO,
    KraiSetting as KraiSettingDTO,
    AiProviderModel as AiProviderModelDTO,
    AIToolDefinition,
    AIToolCall,
    AIFollowUpQuestion,
    AIProviderConfig,
    AIChatConfig,
    ParsedAIResponse,
} from './ai';

// Export AI model types (from existing file)
export type {
    ProviderModel,
    FetchModelsResponse,
    GetModelsResponse,
    UpdateModelResponse,
    OpenAIModelsResponse,
    GoogleModelsResponse,
    GenericModelsResponse,
    ProviderFetchConfig,
    FetchResult,
} from './ai-models';
