/**
 * KRAI Tool Display Registry — metadata for rendering the AI Tools table in Settings.
 *
 * Single source of truth for tool category, badges, use case, input params.
 * Mirrors the function-calling definitions in tools.ts but adds display-only fields.
 */

export interface ToolDisplayInfo {
    name: string;
    category: 'Dashboard' | 'Marketing' | 'Operations' | 'Finance' | 'Occupancy' | 'Booking' | 'Customer' | 'Unit' | 'Expense' | 'Billing';
    description: string;
    capabilities: string[];
    inputParams: string[];
    cached: boolean;
    composite: boolean;
    realtime: boolean;
    requiresDateRange: boolean;
    supportsComparison: boolean;
    bestFor: string;
}

const TOOL_REGISTRY: ToolDisplayInfo[] = [
    // ── Composite Panels ─────────────────────────────────────────────────────
    {
        name: 'get_dashboard_kpi_panel',
        category: 'Dashboard',
        description: 'SATU TOOL untuk semua KPI dashboard: revenue, expense, net profit, transaksi, occupancy, perbandingan, breakdown pengeluaran, status hari ini, ringkasan harian.',
        capabilities: ['Composite', 'Multi-metric', 'Dashboard'],
        inputParams: ['start_date', 'end_date', 'location?'],
        cached: true,
        composite: true,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: true,
        bestFor: 'Pertanyaan dashboard umum — gantikan 4 tool calls sekaligus',
    },
    {
        name: 'get_marketing_panel',
        category: 'Marketing',
        description: 'SATU TOOL untuk semua data marketing: performa marketing, sumber tamu, repeat guests, analisis weekend vs weekday.',
        capabilities: ['Composite', 'Multi-metric', 'Marketing'],
        inputParams: ['start_date', 'end_date', 'location?'],
        cached: true,
        composite: true,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: true,
        bestFor: 'Pertanyaan marketing, sumber tamu, loyalitas',
    },
    {
        name: 'get_operations_panel',
        category: 'Operations',
        description: 'SATU TOOL untuk data operasional: occupancy per lokasi, heatmap jam checkin, performa karyawan, shift, unit underperforming.',
        capabilities: ['Composite', 'Multi-metric', 'Operational'],
        inputParams: ['start_date', 'end_date', 'location?'],
        cached: true,
        composite: true,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: true,
        bestFor: 'Operasional, jam sibuk, kinerja karyawan',
    },
    {
        name: 'get_financial_panel',
        category: 'Finance',
        description: 'SATU TOOL untuk semua data keuangan: profit per lokasi, YoY, tren revenue bulanan, metode pembayaran, tren revenue harian.',
        capabilities: ['Composite', 'Multi-metric', 'Financial'],
        inputParams: ['start_date', 'end_date', 'location?'],
        cached: true,
        composite: true,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: true,
        bestFor: 'Profit, perbandingan tahunan, analisis keuangan',
    },

    // ── Hari Ini (fast, no params) ──────────────────────────────────────────
    {
        name: 'get_daily_summary',
        category: 'Dashboard',
        description: 'RINGKASAN HARI INI vs kemarin — revenue, transaksi, expense, lokasi. Tanpa parameter.',
        capabilities: ['Fast', 'No params', 'Real-time'],
        inputParams: ['(none)'],
        cached: false,
        composite: false,
        realtime: true,
        requiresDateRange: false,
        supportsComparison: false,
        bestFor: '"Gimana kondisi hari ini?", "berapa revenue hari ini?"',
    },
    {
        name: 'get_latest_status',
        category: 'Dashboard',
        description: 'STATUS REAL-TIME — total checkin hari ini, checkout, revenue, tamu yang sedang menginap sekarang.',
        capabilities: ['Fast', 'No params', 'Real-time'],
        inputParams: ['(none)'],
        cached: false,
        composite: false,
        realtime: true,
        requiresDateRange: false,
        supportsComparison: false,
        bestFor: '"Siapa yang lagi nginep?", "status sekarang?"',
    },
    {
        name: 'get_period_summary',
        category: 'Dashboard',
        description: 'Ringkasan bisnis (revenue, expense, transaksi, breakdown lokasi & kategori pengeluaran) untuk rentang tanggal.',
        capabilities: ['Core', 'Revenue', 'Expense'],
        inputParams: ['start_date', 'end_date', 'location?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: false,
        bestFor: 'Periode spesifik (minggu lalu, bulan tertentu)',
    },
    {
        name: 'get_revenue_trend',
        category: 'Finance',
        description: 'DATA TREN REVENUE HARIAN — revenue per hari, rata-rata, hari maksimum/minimum.',
        capabilities: ['Trend', 'Daily', 'Revenue'],
        inputParams: ['start_date', 'end_date', 'location?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: false,
        bestFor: '"Gimana tren 7 hari terakhir?", "hari apa revenue tertinggi?"',
    },
    {
        name: 'compare_periods',
        category: 'Finance',
        description: 'Bandingkan dua periode side-by-side. Otomatis hitung delta dan persentase perubahan.',
        capabilities: ['Comparison', 'Delta', 'Period'],
        inputParams: ['a_start', 'a_end', 'b_start', 'b_end', 'location?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: true,
        bestFor: '"Vs minggu/bulan/tahun lalu"',
    },

    // ── Lokasi & Pelanggan ──────────────────────────────────────────────────
    {
        name: 'get_top_locations',
        category: 'Occupancy',
        description: 'Daftar lokasi apartemen dengan revenue/transaksi tertinggi.',
        capabilities: ['Ranking', 'Location'],
        inputParams: ['start_date', 'end_date', 'limit?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: false,
        bestFor: 'Lokasi terbaik berdasarkan revenue',
    },
    {
        name: 'get_top_customers',
        category: 'Customer',
        description: 'Top customer berdasarkan jumlah kunjungan/pendapatan dalam periode.',
        capabilities: ['Ranking', 'Customer'],
        inputParams: ['start_date', 'end_date', 'limit?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: false,
        bestFor: 'Identifikasi tamu repeat teratas',
    },

    // ── Tagihan & Inventaris ────────────────────────────────────────────────
    {
        name: 'get_outstanding_bills',
        category: 'Billing',
        description: 'Ringkasan tagihan bulanan yang belum dibayar (aging by bucket).',
        capabilities: ['Aging', 'Unpaid', 'Billing'],
        inputParams: ['location?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: false,
        supportsComparison: false,
        bestFor: '"Tagihan apa yang belum dibayar?"',
    },
    {
        name: 'get_unit_inventory',
        category: 'Unit',
        description: 'Status inventory unit saat ini: total kamar, terisi sekarang, tersedia, persentase okupansi.',
        capabilities: ['Real-time', 'Inventory'],
        inputParams: ['location?'],
        cached: false,
        composite: false,
        realtime: true,
        requiresDateRange: false,
        supportsComparison: false,
        bestFor: '"Total kamar?", "kamar kosong sekarang?"',
    },

    // ── Search & Discovery ───────────────────────────────────────────────────
    {
        name: 'search_transactions',
        category: 'Booking',
        description: 'Cari transaksi berdasarkan nama customer, nomor kamar, lokasi, atau ID. Pattern matching fleksibel.',
        capabilities: ['Search', 'Pattern matching'],
        inputParams: ['query', 'start_date?', 'end_date?', 'location?', 'limit?'],
        cached: false,
        composite: false,
        realtime: true,
        requiresDateRange: false,
        supportsComparison: false,
        bestFor: '"Cari transaksi atas nama X", "transaksi kamar 101"',
    },
    {
        name: 'search_expenses',
        category: 'Expense',
        description: 'Cari pengeluaran berdasarkan deskripsi, kategori, atau ID.',
        capabilities: ['Search', 'Expense'],
        inputParams: ['query', 'start_date?', 'end_date?', 'location?', 'category?', 'limit?'],
        cached: false,
        composite: false,
        realtime: true,
        requiresDateRange: false,
        supportsComparison: false,
        bestFor: '"Cari pengeluaran listrik", "expense maintenance"',
    },

    // ── Realtime & Monitoring ────────────────────────────────────────────────
    {
        name: 'get_live_checkins',
        category: 'Customer',
        description: 'Daftar realtime tamu yang sedang check-in sekarang.',
        capabilities: ['Real-time', 'Live'],
        inputParams: ['location?', 'limit?'],
        cached: false,
        composite: false,
        realtime: true,
        requiresDateRange: false,
        supportsComparison: false,
        bestFor: '"Siapa yang lagi nginep?", "kamar mana yang terisi?"',
    },
    {
        name: 'detect_idle_units',
        category: 'Unit',
        description: 'Deteksi unit yang tidak ada transaksi dalam X hari terakhir.',
        capabilities: ['Detection', 'Idle', 'Unit'],
        inputParams: ['days_threshold?', 'location?', 'limit?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: false,
        supportsComparison: false,
        bestFor: '"Kamar mana yang kosong lama?", "unit idle 7 hari"',
    },

    // ── Analytics & Insights ─────────────────────────────────────────────────
    {
        name: 'get_underperforming_units',
        category: 'Unit',
        description: 'Deteksi unit dengan occupancy rate atau revenue di bawah rata-rata.',
        capabilities: ['Analytics', 'Underperforming'],
        inputParams: ['start_date', 'end_date', 'location?', 'threshold?', 'limit?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: false,
        bestFor: '"Unit mana yang performa buruk?", "kamar revenue rendah"',
    },
    {
        name: 'get_weekend_vs_weekday_analysis',
        category: 'Operations',
        description: 'Perbandingan performa weekend (Sabtu-Minggu) vs weekday (Senin-Jumat).',
        capabilities: ['Analysis', 'Comparison'],
        inputParams: ['start_date', 'end_date', 'location?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: true,
        bestFor: '"Lebih ramai weekend atau weekday?"',
    },
    {
        name: 'estimate_month_end_revenue',
        category: 'Finance',
        description: 'Estimasi revenue akhir bulan berdasarkan trend harian saat ini.',
        capabilities: ['Prediction', 'Estimation'],
        inputParams: ['year?', 'month?', 'location?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: false,
        supportsComparison: false,
        bestFor: '"Prediksi revenue bulan ini", "proyeksi revenue"',
    },
    {
        name: 'get_unpaid_bills_detail',
        category: 'Billing',
        description: 'Detail tagihan yang belum dibayar dengan aging analysis.',
        capabilities: ['Detail', 'Aging', 'Unpaid'],
        inputParams: ['location?', 'limit?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: false,
        supportsComparison: false,
        bestFor: '"Detail tagihan unpaid", "aging analysis piutang"',
    },

    // ── Marketing & Customer (NEW 2026-06-01) ────────────────────────────────
    {
        name: 'get_marketing_performance',
        category: 'Marketing',
        description: 'Breakdown transaksi, revenue, fee per marketing.',
        capabilities: ['Marketing', 'Revenue', 'Fee'],
        inputParams: ['start_date', 'end_date', 'location?', 'limit?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: false,
        bestFor: '"Marketing mana paling produktif?", "ROI marketing"',
    },
    {
        name: 'get_repeat_guests',
        category: 'Customer',
        description: 'Daftar tamu yang menginap lebih dari 1x dalam periode, berapa kali, total revenue.',
        capabilities: ['Loyalty', 'Repeat', 'Customer'],
        inputParams: ['start_date', 'end_date', 'location?', 'limit?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: false,
        bestFor: '"Siapa tamu loyal?", "repeat guest analysis"',
    },
    {
        name: 'get_guest_source_summary',
        category: 'Marketing',
        description: 'Dari mana tamu berasal (marketing atau langsung), berapa transaksi dan revenue per sumber.',
        capabilities: ['Source', 'Marketing', 'Direct'],
        inputParams: ['start_date', 'end_date', 'location?', 'limit?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: false,
        bestFor: '"Berapa % tamu dari marketing?", "sumber tamu terbanyak"',
    },

    // ── Durasi & Waktu ──────────────────────────────────────────────────────
    {
        name: 'get_stay_duration_summary',
        category: 'Booking',
        description: 'Distribusi durasi menginap (transit, fullday, per malam, 2+ malam).',
        capabilities: ['Duration', 'Distribution'],
        inputParams: ['start_date', 'end_date', 'location?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: false,
        bestFor: '"Rata-rata durasi menginap?", "pola durasi customer"',
    },
    {
        name: 'get_checkin_heatmap',
        category: 'Operations',
        description: 'Distribusi jam checkin (0-23) dalam periode.',
        capabilities: ['Heatmap', 'Hourly', 'Pattern'],
        inputParams: ['start_date', 'end_date', 'location?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: false,
        bestFor: '"Jam berapa paling ramai checkin?", "peak hour"',
    },
    {
        name: 'get_performance_by_shift',
        category: 'Operations',
        description: 'Perbandingan performa shift (pagi/siang/malam): transaksi, revenue, rata-rata.',
        capabilities: ['Shift', 'Performance'],
        inputParams: ['start_date', 'end_date', 'location?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: false,
        bestFor: '"Shift mana paling produktif?"',
    },

    // ── Expense & Keuangan ───────────────────────────────────────────────────
    {
        name: 'get_expense_breakdown',
        category: 'Expense',
        description: 'Rincian pengeluaran per kategori, total, jumlah transaksi, persentase. Mendukung filter kategori + comparison.',
        capabilities: ['Breakdown', 'Category', 'Comparison'],
        inputParams: ['startDate', 'endDate', 'location?', 'category?', 'comparisonStartDate?', 'comparisonEndDate?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: true,
        bestFor: '"Pengeluaran terbesar kategori apa?", "breakdown biaya"',
    },
    {
        name: 'get_net_profit_per_location',
        category: 'Finance',
        description: 'Revenue, expense, net profit, profit margin per lokasi.',
        capabilities: ['Profit', 'Margin', 'Location'],
        inputParams: ['start_date', 'end_date', 'location?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: false,
        bestFor: '"Lokasi mana paling menguntungkan?", "profit margin"',
    },
    {
        name: 'get_payment_method_summary',
        category: 'Finance',
        description: 'Rasio cash vs transfer per lokasi, total dan persentase.',
        capabilities: ['Payment', 'Cash', 'Transfer'],
        inputParams: ['start_date', 'end_date', 'location?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: false,
        bestFor: '"Berapa % tamu bayar cash?"',
    },

    // ── Occupancy & Trend ────────────────────────────────────────────────────
    {
        name: 'get_occupancy_per_location',
        category: 'Occupancy',
        description: 'Total kamar, transaksi, revenue, occupancy rate per lokasi.',
        capabilities: ['Occupancy', 'Rate', 'Location'],
        inputParams: ['start_date', 'end_date', 'location?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: false,
        bestFor: '"Lokasi mana occupancy tertinggi?"',
    },
    {
        name: 'get_revenue_yoy_comparison',
        category: 'Finance',
        description: 'Perbandingan revenue dan transaksi tahun ini vs tahun lalu untuk periode yang sama.',
        capabilities: ['YoY', 'Comparison', 'Revenue'],
        inputParams: ['start_date', 'end_date', 'location?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: true,
        bestFor: '"Performa tahun ini vs tahun lalu?", "growth YoY"',
    },
    {
        name: 'get_monthly_revenue_trend',
        category: 'Finance',
        description: 'Revenue, transaksi, rata-rata per transaksi per bulan dalam rentang.',
        capabilities: ['Trend', 'Monthly', 'Revenue'],
        inputParams: ['start_date', 'end_date', 'location?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: false,
        bestFor: '"Tren revenue bulanan", "chart pendapatan per bulan"',
    },
    {
        name: 'get_performance_by_employee',
        category: 'Operations',
        description: 'Transaksi dan revenue per karyawan (input_by).',
        capabilities: ['Employee', 'Performance'],
        inputParams: ['start_date', 'end_date', 'location?', 'limit?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: false,
        bestFor: '"Karyawan mana paling produktif?"',
    },

    // ── Analytics DB Tools (2026-06-01) ──────────────────────────────────────
    {
        name: 'get_checkin_busy_hours',
        category: 'Operations',
        description: 'Check-in distribution by hour buckets. Supports date range, comparison, location filter.',
        capabilities: ['Hourly', 'Distribution', 'Comparison'],
        inputParams: ['startDate', 'endDate', 'location?', 'comparisonStartDate?', 'comparisonEndDate?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: true,
        bestFor: '"Jam berapa paling ramai checkin?", "peak hour check-in"',
    },
    {
        name: 'get_occupancy_by_location',
        category: 'Occupancy',
        description: 'Analyze occupancy per apartment location. Returns location_name, total_units, occupied_units, vacancy, rate, comparison, delta, trend.',
        capabilities: ['Occupancy', 'Detailed', 'Comparison'],
        inputParams: ['startDate', 'endDate?', 'location?', 'comparisonStartDate?', 'comparisonEndDate?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: true,
        bestFor: '"Okupansi per lokasi detail dengan perbandingan"',
    },
    {
        name: 'get_billing_breakdown_by_category',
        category: 'Billing',
        description: 'Breakdown billing/transactions by category (paid/unpaid). Returns category, amount, count, percentage, comparison, delta, trend.',
        capabilities: ['Billing', 'Category', 'Comparison'],
        inputParams: ['startDate', 'endDate', 'location?', 'category?', 'comparisonStartDate?', 'comparisonEndDate?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: true,
        bestFor: '"Breakdown tagihan per status paid/unpaid"',
    },
    {
        name: 'get_stay_duration_analysis',
        category: 'Booking',
        description: 'Analyze stay duration types (transit, fullday, promo malam, overnight/regular) with comparison.',
        capabilities: ['Duration', 'Analysis', 'Comparison'],
        inputParams: ['startDate', 'endDate', 'location?', 'comparisonStartDate?', 'comparisonEndDate?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: true,
        bestFor: '"Rata-rata durasi menginap dengan perbandingan"',
    },
    {
        name: 'get_weekday_weekend_analysis',
        category: 'Operations',
        description: 'Analyze weekday vs weekend performance with early day detection.',
        capabilities: ['Weekday', 'Weekend', 'Analysis'],
        inputParams: ['startDate', 'endDate', 'comparisonStartDate?', 'comparisonEndDate?'],
        cached: true,
        composite: false,
        realtime: false,
        requiresDateRange: true,
        supportsComparison: true,
        bestFor: '"Weekday vs weekend analysis"',
    },
    {
        name: 'get_guest_stay_history',
        category: 'Customer',
        description: 'Cari riwayat menginap tamu berdasarkan nama. ILIKE case-insensitive, partial name OK. Jika beberapa nama mirip, return daftar matches untuk klarifikasi.',
        capabilities: ['Search', 'Customer', 'History'],
        inputParams: ['guestName', 'startDate?', 'endDate?', 'location?', 'roomNumber?', 'fuzzyMatch?', 'limit?'],
        cached: false,
        composite: false,
        realtime: true,
        requiresDateRange: false,
        supportsComparison: false,
        bestFor: '"Cari riwayat tamu atas nama X", "berapa kali tamu ini menginap?"',
    },
];

export default TOOL_REGISTRY;

export function getToolByName(name: string): ToolDisplayInfo | undefined {
    return TOOL_REGISTRY.find(t => t.name === name);
}

export function getToolsByCategory(category: string): ToolDisplayInfo[] {
    return TOOL_REGISTRY.filter(t => t.category === category);
}

export function getAllCategories(): string[] {
    return [...new Set(TOOL_REGISTRY.map(t => t.category))];
}
